### ISSUE TITLE
The add button shouldn't disappear when there're not enough tasks to scroll down

### ISSUE THREAD

**Issue by lambej** [AlexForget/to_do_app#26]
![Screenshot_20240106_145948.jpg](https://github.com/AlexForget/to_do_app/assets/81495719/40452d41-c297-41fc-b080-8afdbf1c1aef)

**Comment by AlexForget** [comment]
Yeah, this one I'm aware of, just don't know yet how to fix this 😅

**Comment by AlexForget** [comment]
Will be fix with the next update
